version: '3.7'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - postgrestest
    environment:
      DB_HOST: postgres
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: gorm
      POSTGRES_PASSWORD: gorm
      POSTGRES_DB: gorm
    ports:
      - "5432:5432"
    volumes:
      - pgdata_main:/var/lib/postgresql/data
  postgrestest:
    image: postgres:latest
    environment:
      POSTGRES_USER: gormtest
      POSTGRES_PASSWORD: gormtest
      POSTGRES_DB: gormtest
    ports:
      - "5433:5432"
    volumes:
      - pgdata_test:/var/lib/postgresql/data

volumes:
  pgdata_main:
  pgdata_test:
