version: '3.7'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - postgres-test
    environment:
      DB_HOST: postgres
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: gorm
      POSTGRES_PASSWORD: gorm
      POSTGRES_DB: gorm
    ports:
      - "5432:5432"
    volumes:
      - pgdata_main:/var/lib/postgresql/data
  postgres-test:
    image: postgres:latest
    environment:
      POSTGRES_USER: gorm-test
      POSTGRES_PASSWORD: gorm-test
      POSTGRES_DB: gorm-test
    ports:
      - "5433:5432"
    volumes:
      - pgdata_test:/var/lib/postgresql/data

volumes:
  pgdata_main:
  pgdata_test:
